export const DOMAIN_EVENTS = {
  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_DELETED: "EXPENSE_DELETED",
  SALARY_UPDATED: "SALARY_UPDATED",
  SALARY_LOGGED: "SALARY_LOGGED",

  WATCHLIST_ADDED: "WATCHLIST_ADDED",
  WATCHLIST_UPDATED: "WATCHLIST_UPDATED",
  WATCHLIST_REMOVED: "WATCHLIST_REMOVED",

  INVESTMENT_CREATED: "INVESTMENT_CREATED",
  INVESTMENT_UPDATED: "INVESTMENT_UPDATED",
  INVESTMENT_DELETED: "INVESTMENT_DELETED",

  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED: "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_DELETED: "SUBSCRIPTION_DELETED",

  USER_CREATED: "USER_CREATED",
  USER_DELETED: "USER_DELETED",
} as const;

export type DomainEventType = (typeof DOMAIN_EVENTS)[keyof typeof DOMAIN_EVENTS];

export interface DomainEvent {
  eventType: DomainEventType;

  userId: string;

  userEmail?: string | null;

  entityId?: string;

  eventId?: string;

  itemCount?: number;

  payload?: Record<string, unknown>;
}
